import * as FileSystem from 'expo-file-system/legacy';
import * as Linking from 'expo-linking';
import * as Sharing from 'expo-sharing';
import { useLocalSearchParams } from 'expo-router';
import { useEffect, useState } from 'react';
import { ScrollView } from 'react-native';
import { Body, Button, Card, EmptyState, Eyebrow, H1, H2, LoadingState, Screen } from '../../components/ui';
import { api, ApiError } from '../../lib/api';
import { useAuth } from '../../lib/auth';
import { spacing } from '../../lib/theme';
import type { BriefResponse } from '../../lib/types';

export default function BriefScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const { token } = useAuth();
  const [brief, setBrief] = useState<BriefResponse['brief'] | null>(null);
  const [loading, setLoading] = useState(true);
  const [message, setMessage] = useState('');

  useEffect(() => {
    if (!token || !id) return;
    api.brief(token, id)
      .then((response) => setBrief(response.brief))
      .catch((error) => setMessage(error instanceof ApiError ? error.message : 'Unable to load brief.'))
      .finally(() => setLoading(false));
  }, [id, token]);

  async function shareBrief() {
    if (!brief?.generatedBriefUrl) return;
    const localFile = `${FileSystem.cacheDirectory}answerbrief-${id}.txt`;
    await FileSystem.writeAsStringAsync(localFile, `Your AnswerBrief AI brief is ready:\n${brief.generatedBriefUrl}`);
    if (await Sharing.isAvailableAsync()) {
      await Sharing.shareAsync(localFile);
    } else {
      await Linking.openURL(brief.generatedBriefUrl);
    }
  }

  if (loading) return <LoadingState label="Loading brief..." />;

  if (!brief?.generatedBriefUrl) {
    return (
      <Screen>
        <EmptyState title="Brief not ready yet" body={message || `Current brief status: ${brief?.status || 'not available'}. You will be notified when it is ready.`} />
      </Screen>
    );
  }

  return (
    <ScrollView style={{ flex: 1 }} contentContainerStyle={{ paddingBottom: spacing.xl }}>
      <Screen>
        <Card>
          <Eyebrow>Completed brief</Eyebrow>
          <H1>Your AnswerBrief is ready.</H1>
          <Body>Status: {brief.status}</Body>
        </Card>
        <Card>
          <H2>View, download, or share</H2>
          <Body>The completed brief opens from the secure delivery URL generated by the production workflow.</Body>
          <Button onPress={() => Linking.openURL(brief.generatedBriefUrl as string)}>Open brief</Button>
          <Button secondary onPress={shareBrief}>Download / share link</Button>
        </Card>
      </Screen>
    </ScrollView>
  );
}
